[package]
name = "hogehoge"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true

[workspace]
resolver = "3"
members = [ "plugin-builder","plugins/*", "types"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }

[[bin]]
name = "2hoge"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
extism = "1"
freya = { version = "0.3", features = ["custom-tokio-rt"] }
thiserror = "2.0.12"
tokio = { version = "1", features = ["rt-multi-thread"] }
hogehoge-types = { path = "types" }
