[package]
name = "hogehoge-types"
version = "0.1.0"
edition = "2024"

[dependencies]
extism-convert = { version = "1", default-features = false, features = ["msgpack"] }
uuid = { version = "1", features = ["serde"] }
serde.workspace = true
