[package]
name = "plugin-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
glob = "0.3.2"
wasm-opt = "0.116"
