[package]
name = "hogehoge-db"
version = "0.1.0"
edition = "2024"

[dependencies]
hogehoge-types.workspace = true

sqlx.workspace = true
sea-query.workspace = true
sea-query-binder.workspace = true

tracing.workspace = true
